---
title: "Colours"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Colours}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(ggplot2)

print_pal2 <- function(pal_name) {
  ggplot(
    data     = data.frame(pal = sgplot::sg_colour_palettes[[pal_name]]),
    mapping  = aes(x = seq_along(.data$pal),
                   y = 1,
                   fill = factor(seq_along(.data$pal)))
  ) +
    geom_tile() +
    sgplot::scale_fill_discrete_sg(pal_name) +
    theme_void() +
    theme(legend.position = "none")
}

```

The following colour palettes are available to use in `sgplot`:

**main**

```{r, echo = FALSE, fig.height = 1}
print_pal2("main")
```

**main2**

```{r, echo = FALSE, fig.height = 1}
print_pal2("main2")
```

**main6**

```{r, echo = FALSE, fig.height = 1}
print_pal2("main6")
```

**sequential**

```{r, echo = FALSE, fig.height = 1}
print_pal2("sequential")
```

**focus**

```{r, echo = FALSE, fig.height = 1}
print_pal2("focus")
```
